# node/Dockerfile
FROM golang:1.25 AS builder
WORKDIR /app
COPY . .
RUN GOOS=linux GOARCH=arm64 go build -o node ./kos/cmd/node/main.go

FROM scratch
COPY --from=builder /app/node .
ENTRYPOINT ["./node"]