gateway:
  image:
    repository: mem0z/kos-gateway
    tag: latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80

node:
  image:
    repository: mem0z/kos-node
    tag: latest
  replicaCount: 3
  persistence:
    storageClass: standard
    size: 1Gi
    accessModes:
      - ReadWriteOnce

valkey:
  enabled: true
  architecture: standalone
  image:
    tag: "latest"
    pullPolicy: Always
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
  auth:
    enabled: false    